petah-sama/dragons-r-us

Gemfile, Gemfile.lock, app/models/user.rb, config/environments/development.rb, config/environments/production.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20200224154350_devise_create_users.rb, test/models/user_test.rb
=> Started the devise authentication (Margarida)

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_colors.scss, app/views/layouts/application.html.erb
- navbar orange
- replaced LW logo with app title (missing logo)
- added relevant menu to dropdown
- added avatar
=> Front end navbar

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb
=> footer done

app/models/dragon.rb, db/migrate/20200224163856_create_dragons.rb, db/schema.rb, test/models/dragon_test.rb
É preciso fazer db:migrate, 
Criei os models
=> created Dragon model, migrated Dragon and Users

app/models/dragon.rb
Added validations to the Dragon Model
=> Model validations

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/config/_colors.scss, db/schema.rb
=> Front end footer

app/controllers/dragons_controller.rb, app/views/dragons/edit.html.erb, app/views/dragons/index.html.erb, app/views/dragons/new.html.erb, app/views/dragons/show.html.erb, config/routes.rb, test/controllers/dragons_controller_test.rb
- dragons controller
- dragons routes
- booking routes
=> dragons controller

app/controllers/application_controller.rb, app/controllers/dragons_controller.rb, app/models/dragon.rb, app/views/dragons/_form.html.erb, app/views/dragons/edit.html.erb, app/views/dragons/new.html.erb, db/migrate/20200224180948_fix_type_column_name.rb, db/migrate/20200224181950_remove_location_column.rb, db/schema.rb
added a lot of things
removed location column
=> Dragons partial form

Gemfile, Gemfile.lock
=> added faker to gemfile

app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, db/migrate/20200224190010_add_first_name_to_users.rb, db/migrate/20200224190448_add_last_name_to_users.rb, db/schema.rb
Added name to form, added names to User Table and wrote the permissio…ns for the User in the Application Controller
=> Finished the User model (Schema Change)

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_container-dragons-index.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/dragons/index.html.erb, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb
Dragons index page is now centred, and the footer is no longer covering the content, but it is sticky
=> Dragons index

app/assets/stylesheets/components/_footer.scss
=> fixed footer

app/controllers/pages_controller.rb, app/policies/dragon_policy.rb, app/views/pages/my_dragons.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
=> added my-dragons page

Gemfile
=> removed duplicate dotenv-rails

app/controllers/dragons_controller.rb, app/policies/dragon_policy.rb
=> fixed pundit

app/views/dragons/index.html.erb, app/views/dragons/show.html.erb, app/views/pages/my_dragons.html.erb
Included also the back button and the show button (on the name and on the dragon picture)
=> thumbnail on dragons index

app/views/shared/_navbar.html.erb
=> added a breed a dragon option on navbar for registered users

app/models/booking.rb
You can call booking.total_price to get the total price of a booking.
=> Total_price works

app/controllers/pages_controller.rb, app/policies/booking_policy.rb, app/policies/dragon_policy.rb, app/views/pages/my_bookings.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
=> Bookings index

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_hero.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
maltinha é assim, a landing podia tar melhor, mas se mudarmos as cores é capaz de ficar tranquilo.
mudei a font da navbar. a font que lá esta é a mesma do hero, e pode ser usada quando quisermos, adicionei as fonts. Chama-se 'Marcellus' 😂
acho que foi só isso
=> landing almost done, minor style fixes

Gemfile, Gemfile.lock, app/models/dragon.rb, config/initializers/geocoder.rb, db/migrate/20200226115447_add_coordinates_to_dragons.rb, db/migrate/20200226121419_add_available_to_dragons.rb, db/migrate/20200226121556_change_available_from_dragons.rb, db/schema.rb
Added the location (coordinates) 
Added the adress
Added the available (boolean - default:true)
=> Created locations, adress and available (Schema change)

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_main.scss, app/assets/stylesheets/components/_sidebar.scss, app/views/layouts/application.html.erb, app/views/shared/_sidebar.html.erb
=> sidebar quase la

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_container-dragons-index.scss, app/views/dragons/_list.html.erb
=> beautiful cards with font awesome

app/assets/stylesheets/components/_calendar.scss, app/assets/stylesheets/components/_card-show-dragon.scss, app/views/bookings/_list.html.erb, app/views/dragons/show.html.erb
=> calendar a little bit better

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_sidebar.scss, app/controllers/dragons_controller.rb, app/controllers/pages_controller.rb, app/models/dragon.rb, app/views/shared/_navbar.html.erb
=> basic search bar implemented

app/controllers/bookings_controller.rb, app/views/shared/_flashes.html.erb
=> you cannot book booked dragons anymore :D

app/controllers/dragons_controller.rb
when you click create a dragon you are redirected to the show page of the dragon you created
=> Breed dragon redirect

app/views/pages/home.html.erb
Check image preview, minor change done. merge if you like, close if you don't,  no offence taken 😂😂😂
=> minor change made to landing

app/views/devise/registrations/edit.html.erb, app/views/dragons/_form.html.erb, app/views/dragons/edit.html.erb, app/views/dragons/new.html.erb
DRAGONS
new
edit
amazing
cenas
=> new edit dragon OK

app/assets/stylesheets/components/_card-show-dragon.scss, app/assets/stylesheets/components/_container-dragons-show.scss, app/controllers/pages_controller.rb, app/views/bookings/_list.html.erb, app/views/bookings/_new.html.erb, app/views/dragons/show.html.erb
=> show card dragon
